### PR TITLE
Install manifest and package marker

### PR DESCRIPTION
**Pull request by ivanpauno**
Follow up of https://github.com/colcon/colcon-ros/pull/74.

Also, maybe fix https://github.com/ros2/ament_cmake_ros/issues/5

### CODE REVIEW

**Comment by pbaughman** [comment]
:-( Sorry about that

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8114/)

**Comment by ivanpauno** [comment]
@dirk-thomas can you merge?
I don't have write access in this repo at the moment.

**Comment by dirk-thomas** [comment]
> I don't have write access in this repo at the moment.

Now you do.

**Pull request merged**
