### PR TITLE
Add isolated gmock test

### PR DESCRIPTION
**Pull request by pbaughman**
While trying to isolated the rosbag2 tests, I noticed two things:

1) Rosbag2 uses ament_add_gmock, not ament_add_gtest
2) The tests for the domain_coordinator itself can be interfered with by tests using the domain_coordinator (if running in parallel)

Fix 1 by adding ament_cmake_ros_isolated_gmock (depends on [this PR](https://github.com/ament/ament_cmake/pull/177))

Fix 2 by having the tests for the domain coordinator run using a different set of ports.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
See comment on https://github.com/ros2/ament_cmake_ros/pull/3#issuecomment-500936186.

**Comment by pbaughman** [comment]
@dirk-thomas Yeah - if you're OK with moving everything into ament_cmake_ros, I'm happy to do it.

Is the assumption that if you're using ament_cmake_ros, you already deep enough into the dependency graph that it's safe to add both ament_cmake_pytest and ament_cmake_gtest even if you only plan on using one of them

**Comment by dirk-thomas** [comment]
> Is the assumption that if you're using ament_cmake_ros, you already deep enough into the dependency graph that it's safe to add both ament_cmake_pytest and ament_cmake_gtest even if you only plan on using one of them

Yeah, that would be my thinking. @wjwwood Since you merged this what do you think about reintegrating these into `ament_cmake_ros`?

**Comment by wjwwood** [comment]
That’s fine with me.

**Comment by pbaughman** [comment]
@dirk-thomas Ok - I've mashed everything into ament_cmake_ros now, too.  Tested with isolated tests in rcl (gtest) rclpy (pytest) and rosbag2 (gmock)

The dependency graph of ament_cmake_ros used to look like this:
```
ament_flake8                            +  *       *     ***       *    ..
ament_package                            +* ....... ....    .......... ...
ament_cmake_core                          + ******* ****    ****.***** **.
ament_pep257                               +       *     ***        *   ..
ament_cmake_export_definitions              +               *   .        .
ament_cmake_export_include_directories       +              *   .        .
ament_cmake_export_libraries                  +      *      *   .        .
ament_cmake_export_link_flags                  +            *   .        .
ament_cmake_include_directories                 +     *     .   .        .
ament_cmake_libraries                            +  * *     *   .       ..
ament_cmake_python                                +    *    *   .        .
ament_copyright                                    +    ****   * .....*...
ament_cmake_export_dependencies                     +       *   .       *.
ament_cmake_export_interfaces                        +      *   .        .
ament_cmake_target_dependencies                       +     *   .        .
ament_cmake_test                                       +    ****.***** *..
ament_cppcheck                                          +        *      ..
ament_cpplint                                            +        *     ..
ament_lint_cmake                                          +  * . ..... ...
ament_xmllint                                              +         *  ..
ament_cmake                                                 +   *        *
ament_cmake_lint_cmake                                       + * ***** **.
ament_lint_auto                                               +          *
ament_cmake_copyright                                          + ***** **.
uncrustify_vendor                                               +     *...
ament_cmake_cppcheck                                             +      *.
ament_cmake_cpplint                                               +     *.
ament_cmake_flake8                                                 +    *.
ament_cmake_pep257                                                  +   *.
ament_cmake_xmllint                                                  +  *.
ament_uncrustify                                                      +*..
ament_cmake_uncrustify                                                 +*.
ament_lint_common                                                       +*
ament_cmake_ros                                                          +
```

After this PR it will look like this:
```
ament_flake8                            +   *        *     ****          *    ..
ament_package                            + *  ....... ....     ............. ...
gtest_vendor                              +  *                  *    .         .
ament_cmake_core                           +  ******* ****     *******.***** **.
ament_pep257                                +        *     ****           *   ..
gmock_vendor                                 +                       *         .
ament_cmake_export_definitions                +                *      .        .
ament_cmake_export_include_directories         +               *      .        .
ament_cmake_export_libraries                    +      *       *      .        .
ament_cmake_export_link_flags                    +             *      .        .
ament_cmake_include_directories                   +     *      .      .        .
ament_cmake_libraries                              +  * *      *      .       ..
ament_cmake_python                                  +    *     *      .        .
ament_copyright                                      +    *****     *  .....*...
ament_cmake_export_dependencies                       +        *      .       *.
ament_cmake_export_interfaces                          +       *      .        .
ament_cmake_target_dependencies                         +      *      .        .
ament_cmake_test                                         +     *******.***** *..
ament_cppcheck                                            +            *      ..
ament_cpplint                                              +            *     ..
ament_lint_cmake                                            +    *  .  ..... ...
ament_xmllint                                                +             *  ..
domain_coordinator                                            +                *
ament_cmake                                                    +      *        *
ament_cmake_gtest                                               +    *         *
ament_cmake_lint_cmake                                           +  *  ***** **.
ament_cmake_pytest                                                +            *
ament_lint_auto                                                    +           *
ament_cmake_copyright                                               +  ***** **.
ament_cmake_gmock                                                    +         *
uncrustify_vendor                                                     +     *...
ament_cmake_cppcheck                                                   +      *.
ament_cmake_cpplint                                                     +     *.
ament_cmake_flake8                                                       +    *.
ament_cmake_pep257                                                        +   *.
ament_cmake_xmllint                                                        +  *.
ament_uncrustify                                                            +*..
ament_cmake_uncrustify                                                       +*.
ament_lint_common                                                             +*
ament_cmake_ros                                                                +
```

**Comment by pbaughman** [comment]
@wjwwood I think this is good to go

**Comment by wjwwood** [comment]
Quick CI up to `ament_cmake_ros`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7367/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3525/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6042/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7190/)

**Comment by wjwwood** [comment]
Looks like there are some linting issues that need to be resolved.

**Comment by pbaughman** [comment]
*sigh* on it!

**Comment by wjwwood** [comment]
Cool, new CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7368/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3526/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6043/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7191/)

**Pull request merged**
